module.exports = {
  login: "billgates",
  id: 105379,
  node_id: "MDQ6VXNlcjEwNTM3OQ==",
  avatar_url: "https://avatars.githubusercontent.com/u/105379?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/billgates",
  html_url: "https://github.com/billgates",
  followers_url: "https://api.github.com/users/billgates/followers",
  following_url:
    "https://api.github.com/users/billgates/following{/other_user}",
  gists_url: "https://api.github.com/users/billgates/gists{/gist_id}",
  starred_url: "https://api.github.com/users/billgates/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/billgates/subscriptions",
  organizations_url: "https://api.github.com/users/billgates/orgs",
  repos_url: "https://api.github.com/users/billgates/repos",
  events_url: "https://api.github.com/users/billgates/events{/privacy}",
  received_events_url: "https://api.github.com/users/billgates/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 2,
  public_gists: 0,
  followers: 15,
  following: 0,
  created_at: "2009-07-15T20:37:16Z",
  updated_at: "2021-02-04T11:50:12Z",
};
